chess/board/urls.py
from django.urls import path

from .views import *

app_name = 'board'

urlpatterns = [
    path('game/', index, name="game"),
]

chess/chats/urls.py
from django.urls import path

from .views import *

app_name = 'chats'

urlpatterns = [
    path('', chat_view, name='chat'),
    path("<str:room_name>/", room_view, name='room')
]

chess/chess/urls.py
from django.contrib import admin
from django.urls import path, include
from board.views import first_page
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', first_page, name='main'),
    path('board/', include('board.urls')),
    path('users/', include('users.urls')),
    path('chats/', include('chats.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

chess/users/urls.py
from django.urls import path

from .views import *

app_name = 'users'

urlpatterns = [
    
    path('login/', login_viev, name='login'),
    path('logout/', logout_viev, name='logout'),
    path('registration/', registration_viev, name='regist'),
]

chess/board/models.py
from django.db import models

class User(models.Model):
    login = models.CharField(max_length=100)
    mail = models.EmailField(max_length=100)


class Statistic(models.Model):
    user_name = models.ForeignKey(User, on_delete=models.CASCADE)
    numb_game = models.IntegerField()
    won_game = models.IntegerField()
    lost_game = models.IntegerField()

chess/chats/models.py
from django.db import models

# Create your models here.

chess/board/views.py
from django.shortcuts import render


# def index(request):
#     return render(request, 'board/center/board.html')

def index(request):
    return render(request, 'board/center/sec_board.html')

def first_page(request):
    return render(request, 'board/main.html')

chess/chats/views.py
from django.shortcuts import render

def chat_view(requests):
    return render (requests, 'chats/chats.html')


def room_view(requests, room_name):
    return render (requests, 'chats/room.html', {'room_name': room_name})

chess/users/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse

from .form import LogForm, RegistForm



def login_viev(request):
    if request.method == 'POST':
        form = LogForm(request.POST)
        
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd['username'], password=cd['password'])
            if user: 
                login(request, user)
                return HttpResponseRedirect(reverse('board:game'))
    
    else:
        form = LogForm

    return render(request, 'users/auth.html', {'form': form})


def registration_viev(request):
    if request.method == 'POST':
        form = RegistForm(request.POST)
        
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(form.cleaned_data['password1'])
            new_user.save()
            
            
            return HttpResponseRedirect(reverse('users:login'))
            
    
    else:
        form = RegistForm

    return render(request, 'users/regist.html', {'form': form})


def logout_viev(request):
    logout(request)
    print('user_logout')
    return HttpResponseRedirect(reverse('users:login'))
   
   
  

chess/board/templates/board/bottom/bottom.html
    <div class="bottom">
        <div class="git">
            <a href="https://github.com/alexmais95/Chess">GIT_sorce</a>
        </div>
        <div class="mail">
            <a href="https://alexlove9596@gmail.com">alexlove9596@gmail.com</a>
        </div>
    </div>

chess/board/templates/board/center/board.html
{% extends "board/main.html" %}


{% block center %}
    <div class="dad-container">
        <div></div>
        <div class="main-container">
          
          <div class="file-a files">
            <div class="square">rook_b</div>
            <div class="square">pown_b</div>
            <div class="square"></div>
            <div class="square"></div>
            <div class="square"></div>
            <div class="square"></div>
            <div class="square">pown_w</div>
            <div class="square">rook_w</div>
          </div>
          
          
          <div class="file-b files">
            <div class="square">knight_b</div>
            <div class="square">pown_b</div>
            <div class="square"></div>
            <div class="square"></div>
            <div class="square"></div>
            <div class="square"></div>
            <div class="square">pown_w</div>
            <div class="square">knight_w</div>
          </div>
          
          
          <div class="file-c files">
            <div class="square">bishop_b</div>
            <div class="square">pown_b</div>
            <div class="square"></div>
            <div class="square"></div>
            <div class="square"></div>
            <div class="square"></div>
            <div class="square">pown_w</div>
            <div class="square">bishop_w</div>
          </div>
          
          
          <div class="file-d files">
            <div class="square">king_b</div>
            <div class="square">pown_b</div>
            <div class="square"></div>
            <div class="square"></div>
            <div class="square"></div>
            <div class="square"></div>
            <div class="square">pown_w</div>
            <div class="square">king_w</div>
          </div>
          
          
          <div class="file-e files">
            <div class="square">queen_b</div>
            <div class="square">pown_b</div>
            <div class="square"></div>
            <div class="square"></div>
            <div class="square"></div>
            <div class="square"></div>
            <div class="square">pown_w</div>
            <div class="square">queen_w</div>
          </div>
          
          
          <div class="file-f files">
            <div class="square">bishop_b</div>
            <div class="square">pown_b</div>
            <div class="square"></div>
            <div class="square"></div>
            <div class="square"></div>
            <div class="square"></div>
            <div class="square">pown_w</div>
            <div class="square">bishop_w</div>
          </div>
          
          <div class="file-g files">
            <div class="square">knight_b</div>
            <div class="square">pown_b</div>
            <div class="square"></div>
            <div class="square"></div>
            <div class="square"></div>
            <div class="square"></div>
            <div class="square">pown_w</div>
            <div class="square">knight_w</div>
          </div>
          
          <div class="file-h files">
            <div class="square">rook_b</div>
            <div class="square">pown_b</div>
            <div class="square"></div>
            <div class="square"></div>
            <div class="square"></div>
            <div class="square"></div>
            <div class="square">pown_w</div>
            <div class="square">rook_w</div>
          </div>
        </div>
        <div class="menu">
          <div class="user1">User-1</div>
          <div class="info">
            <div class="turn w">White turn</div>
          </div>
          <div class="user1">{{user.username}}</div>
        </div>
      </div>
    
{% endblock %}

chess/board/templates/board/center/sec_board.html
{% extends "board/main.html" %}


{% block center %}
    <div class="dad-container">
        <div></div>
        <div class="board-container">
           
        </div>
        <div class="menu">
          <div class="user1">User-1</div>
          <div class="info">
            <div class="turn w">White turn</div>
          </div>
          <div class="user1">{{user.username}}</div>
        </div>
      </div>
    
{% endblock %}

chess/board/templates/board/header/header.html
    <div class="header_left">
        
    </div>
    
    <div class="header_center">
        <h1 class="logo">MAIS - CHESS</h1>
    </div>
    
    <div class="header_right">
        {% if user.is_authenticated %}
           <a class="log_out" href="{% url 'users:logout' %}">
            <h1>Logout</h1>
           </a>
            <h1 class="user_name">{{user.username}}</h1>
        {% else %}
           <a class="login" href="{% url 'users:login' %}">
                <h1 class="user">Login</h1>
           </a> 
           
           <a class="regist" href="{% url 'users:regist' %}">
                <h1 class="user">Registration</h1>
            </a> 
        {% endif %}
    </div>

chess/board/templates/board/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Chess</title>
    <link rel="icon" href="data:;base64,=">
    <link rel="stylesheet" href="{% static 'board/style/style.css' %}" />
</head>

<body>
    
    <div class="dad-container">
        <div class="main-container">
          
          <div class="file-a files">
            <div class="square">rook_b</div>
            <div class="square">pown_b</div>
            <div class="square"></div>
            <div class="square"></div>
            <div class="square"></div>
            <div class="square"></div>
            <div class="square">pown_w</div>
            <div class="square">rook_w</div>
          </div>
          
          
          <div class="file-b files">
            <div class="square">knight_b</div>
            <div class="square">pown_b</div>
            <div class="square"></div>
            <div class="square"></div>
            <div class="square"></div>
            <div class="square"></div>
            <div class="square">pown_w</div>
            <div class="square">knight_w</div>
          </div>
          
          
          <div class="file-c files">
            <div class="square">bishop_b</div>
            <div class="square">pown_b</div>
            <div class="square"></div>
            <div class="square"></div>
            <div class="square"></div>
            <div class="square"></div>
            <div class="square">pown_w</div>
            <div class="square">bishop_w</div>
          </div>
          
          
          <div class="file-d files">
            <div class="square">king_b</div>
            <div class="square">pown_b</div>
            <div class="square"></div>
            <div class="square"></div>
            <div class="square"></div>
            <div class="square"></div>
            <div class="square">pown_w</div>
            <div class="square">king_w</div>
          </div>
          
          
          <div class="file-e files">
            <div class="square">queen_b</div>
            <div class="square">pown_b</div>
            <div class="square"></div>
            <div class="square"></div>
            <div class="square"></div>
            <div class="square"></div>
            <div class="square">pown_w</div>
            <div class="square">queen_w</div>
          </div>
          
          
          <div class="file-f files">
            <div class="square">bishop_b</div>
            <div class="square">pown_b</div>
            <div class="square"></div>
            <div class="square"></div>
            <div class="square"></div>
            <div class="square"></div>
            <div class="square">pown_w</div>
            <div class="square">bishop_w</div>
          </div>
          
          <div class="file-g files">
            <div class="square">knight_b</div>
            <div class="square">pown_b</div>
            <div class="square"></div>
            <div class="square"></div>
            <div class="square"></div>
            <div class="square"></div>
            <div class="square">pown_w</div>
            <div class="square">knight_w</div>
          </div>
          
          <div class="file-h files">
            <div class="square">rook_b</div>
            <div class="square">pown_b</div>
            <div class="square"></div>
            <div class="square"></div>
            <div class="square"></div>
            <div class="square"></div>
            <div class="square">pown_w</div>
            <div class="square">rook_w</div>
          </div>
        </div>
      </div>
    
    <script type="module" src="{% static 'board/javascript/main.js' %}"></script>


</body>
    
</html>

chess/board/templates/board/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chess</title>
    <link rel="icon" href="data:;base64,=">
    <link rel="stylesheet" href="{% static 'board/style/style.css' %}" />
</head>
<body>
    <div id="header_spaces">
        {% include 'board/header/header.html' %}
    </div>
    
    <div id="center_spaces">
        {% block center %}
        {% endblock %}
    </div>
    
    <div id="bottom_spaces">
        {% include 'board/bottom/bottom.html' %}
    </div>

    <script type="module" src="{% static 'board/javascript/OOP_logic/main.js' %}"></script>
    
</body>
</html>

chess/chats/templates/chats/chats.html
{% extends "board/main.html" %}


{% block center %}
What chat room would you like to enter?<br>
<input id="room-name-input" type="text" size="100"><br>
<input id="room-name-submit" type="button" value="Enter">

<script>
    document.querySelector('#room-name-input').focus();
    document.querySelector('#room-name-input').onkeyup = function(e) {
        if (e.key === 'Enter') {  // enter, return
            document.querySelector('#room-name-submit').click();
        }
    };

    document.querySelector('#room-name-submit').onclick = function(e) {
        var roomName = document.querySelector('#room-name-input').value;
        window.location.pathname = '/chats/' + roomName + '/';
    };
</script>
{% endblock %}

chess/chats/templates/chats/room.html
{% extends "board/main.html" %}


{% block center %}
    
    <div class="chat_room">
        <div class="chat_arey">
            <textarea id="chat-log" cols="100" rows="20"></textarea><br>
        </div>
        
        <div class="chat_input_arey">
            <input id="chat-message-input" type="text" size="100"><br>
        </div>
        
        <div class="chat_submit_arey">
            <input id="chat-message-submit" type="button" value="Send">
        </div>
        
        {{ room_name|json_script:"room-name" }}
    </div> 
    <script>
        const roomName = JSON.parse(document.getElementById('room-name').textContent);
            
            let username = document.getElementsByClassName('user_name')

            const chatSocket = new WebSocket('ws://' + window.location.host + '/ws/chats/'+ roomName + '/');
            
            chatSocket.onmessage = function(e) {
                const data = JSON.parse(e.data);
                            
                if(username.length == 0) {
                    document.querySelector('#chat-log').value += ('anonim' +': '+ data.message + '\n');
                }else{
                    document.querySelector('#chat-log').value += (username[0].innerHTML +': '+ data.message + '\n');
                }
                            
                };
            
            chatSocket.onclose = function(e) {
                console.error('Chat socket closed unexpectedly');
            };
            
            document.querySelector('#chat-message-input').focus();
            
            document.querySelector('#chat-message-input').onkeyup = function(e) {
                if (e.key === 'Enter') {  // enter, return
                    document.querySelector('#chat-message-submit').click();
                }
            };
            
                        
            document.querySelector('#chat-message-submit').onclick = function(e) {
                
                const messageInputDom = document.querySelector('#chat-message-input');
                const message = messageInputDom.value;
                
                chatSocket.send(JSON.stringify({
                    'message': message
                }));
                
                messageInputDom.value = '';
            };

    </script>
    
    
{% endblock %}

chess/users/templates/users/auth.html
{% extends "board/main.html" %}



{% block center %}
<div class="logg">
    {% if form.errors %}
        <p>Your username and password didn't match. Please try again.</p>
    {% endif %}
    
    <div class="loggin_user">
        <form class="form_main" method="post" name="loggin">
            {% csrf_token %}
            <div class="form_log">
                {{form.username.errors}}
                <label for="{{form.username.id_for_label}}">Ваш логін</label>
                {{form.username}}
            </div>
            <div class="form_log">
                
                <label for="form.password.id_for_label">Ваш пароль</label>
                {{form.password.errors}}
                {{form.password}}
                
            </div>
            <div class="form_log">
                <input class="submit" type="submit" value="Увійти">
                {{form.submit}}
            </div>
            
        </form>
    </div>
</div>

{% endblock %}

chess/users/templates/users/regist.html
{% extends "board/main.html" %}



{% block center %}
<div class="logg">
    {% if form.errors %}
        <p>Your username and password didn't match. Please try again.</p>
    {% endif %}
    
    <div class="regist_user">
        <form class="form_main_regist" method="post" name="loggin">
            {% csrf_token %}
            
            <div class="form_log">
                
                <p>Вигадайте логін</p>
                {{form.username}}
            </div>
            
            <div class="form_log">
                
                <p>Тепер пароль</p>
                {{form.password1}}
                
            </div>

            <div class="form_log">
                
                <p>Повторіть пароль</p>
                {{form.password2}}
                
            </div>
            
            <div class="form_log">
                <input class="submit_regist" type="submit" value="Реєстрація">
                {{form.submit}}
            </div>
            
        </form>
    </div>
</div>

{% endblock %}